---
- name: Gather user information
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: Checking NETCONF connectivity
      wait_for: host={{ inventory_hostname }} port=22 timeout=5

    - name: Install Junos OS package
      collections:
        - juniper.device
      software:
        reboot: true
        version: "{{ os_version }}"
        package: "{{ local_package }}/{{ os_package }}"
        logfile: "{{ log_dir }}/software.log"
      register: sw
      notify:
        - wait_reboot

